#!/bin/csh
#$ -q long # Specify queue
#$ -M NETID@nd.edu    # Email address for job notification
#$ -m a                # Send mail when job aborts
#$ -V # use all of my environment variables
#$ -t 1-3:1 # submit an array of jobs, with the numbers 1-3, iterated by 1
# the array index is stored in the variable ${SGE_TASK_ID}


module load python # python 2.7.8 instead of system default 2.6.6

cd $PYTHONPATH/template/ # change to the current directory
./run_3v.py --maxEpochs=${SGE_TASK_ID}


